FROM mcr.microsoft.com/playwright:focal

# Install app dependencies
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --production

# Copy server
COPY playwright-server.js ./

EXPOSE 3001
CMD ["node", "playwright-server.js"]
