/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSourcingRouteImport } from './routes/_app/sourcing'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSequencesRouteImport } from './routes/_app/sequences'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppDeliverabilityRouteImport } from './routes/_app/deliverability'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as ApiPublicTrackOpenDotgifRouteImport } from './routes/api/public/track/open[.]gif'
import { Route as ApiPublicTrackClickRouteImport } from './routes/api/public/track/click'
import { Route as ApiPublicCronImapPollRouteImport } from './routes/api/public/cron/imap-poll'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSourcingRoute = AppSourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSequencesRoute = AppSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliverabilityRoute = AppDeliverabilityRouteImport.update({
  id: '/deliverability',
  path: '/deliverability',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackOpenDotgifRoute =
  ApiPublicTrackOpenDotgifRouteImport.update({
    id: '/api/public/track/open.gif',
    path: '/api/public/track/open.gif',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackClickRoute = ApiPublicTrackClickRouteImport.update({
  id: '/api/public/track/click',
  path: '/api/public/track/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronImapPollRoute = ApiPublicCronImapPollRouteImport.update({
  id: '/api/public/cron/imap-poll',
  path: '/api/public/cron/imap-poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deliverability': typeof AppDeliverabilityRoute
  '/leads': typeof AppLeadsRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/sequences': typeof AppSequencesRoute
  '/settings': typeof AppSettingsRoute
  '/sourcing': typeof AppSourcingRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/cron/imap-poll': typeof ApiPublicCronImapPollRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/track/open.gif': typeof ApiPublicTrackOpenDotgifRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deliverability': typeof AppDeliverabilityRoute
  '/leads': typeof AppLeadsRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/sequences': typeof AppSequencesRoute
  '/settings': typeof AppSettingsRoute
  '/sourcing': typeof AppSourcingRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/cron/imap-poll': typeof ApiPublicCronImapPollRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/track/open.gif': typeof ApiPublicTrackOpenDotgifRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deliverability': typeof AppDeliverabilityRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sequences': typeof AppSequencesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sourcing': typeof AppSourcingRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/cron/imap-poll': typeof ApiPublicCronImapPollRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/track/open.gif': typeof ApiPublicTrackOpenDotgifRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/deliverability'
    | '/leads'
    | '/pipeline'
    | '/reports'
    | '/sequences'
    | '/settings'
    | '/sourcing'
    | '/api/public/unsubscribe'
    | '/api/public/cron/imap-poll'
    | '/api/public/track/click'
    | '/api/public/track/open.gif'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/deliverability'
    | '/leads'
    | '/pipeline'
    | '/reports'
    | '/sequences'
    | '/settings'
    | '/sourcing'
    | '/api/public/unsubscribe'
    | '/api/public/cron/imap-poll'
    | '/api/public/track/click'
    | '/api/public/track/open.gif'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/campaigns'
    | '/_app/dashboard'
    | '/_app/deliverability'
    | '/_app/leads'
    | '/_app/pipeline'
    | '/_app/reports'
    | '/_app/sequences'
    | '/_app/settings'
    | '/_app/sourcing'
    | '/api/public/unsubscribe'
    | '/api/public/cron/imap-poll'
    | '/api/public/track/click'
    | '/api/public/track/open.gif'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiPublicCronImapPollRoute: typeof ApiPublicCronImapPollRoute
  ApiPublicTrackClickRoute: typeof ApiPublicTrackClickRoute
  ApiPublicTrackOpenDotgifRoute: typeof ApiPublicTrackOpenDotgifRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sourcing': {
      id: '/_app/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof AppSourcingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sequences': {
      id: '/_app/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof AppSequencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliverability': {
      id: '/_app/deliverability'
      path: '/deliverability'
      fullPath: '/deliverability'
      preLoaderRoute: typeof AppDeliverabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/open.gif': {
      id: '/api/public/track/open.gif'
      path: '/api/public/track/open.gif'
      fullPath: '/api/public/track/open.gif'
      preLoaderRoute: typeof ApiPublicTrackOpenDotgifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/click': {
      id: '/api/public/track/click'
      path: '/api/public/track/click'
      fullPath: '/api/public/track/click'
      preLoaderRoute: typeof ApiPublicTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/imap-poll': {
      id: '/api/public/cron/imap-poll'
      path: '/api/public/cron/imap-poll'
      fullPath: '/api/public/cron/imap-poll'
      preLoaderRoute: typeof ApiPublicCronImapPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliverabilityRoute: typeof AppDeliverabilityRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSequencesRoute: typeof AppSequencesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcingRoute: typeof AppSourcingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampaignsRoute: AppCampaignsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeliverabilityRoute: AppDeliverabilityRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppReportsRoute: AppReportsRoute,
  AppSequencesRoute: AppSequencesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcingRoute: AppSourcingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiPublicCronImapPollRoute: ApiPublicCronImapPollRoute,
  ApiPublicTrackClickRoute: ApiPublicTrackClickRoute,
  ApiPublicTrackOpenDotgifRoute: ApiPublicTrackOpenDotgifRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
