/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSequencesRouteImport } from './routes/_app/sequences'
import { Route as AppPlaybookRouteImport } from './routes/_app/playbook'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppLeadFinderRouteImport } from './routes/_app/lead-finder'
import { Route as AppEmailFinderRouteImport } from './routes/_app/email-finder'
import { Route as AppDeliverabilityRouteImport } from './routes/_app/deliverability'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSequencesRoute = AppSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybookRoute = AppPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadFinderRoute = AppLeadFinderRouteImport.update({
  id: '/lead-finder',
  path: '/lead-finder',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailFinderRoute = AppEmailFinderRouteImport.update({
  id: '/email-finder',
  path: '/email-finder',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliverabilityRoute = AppDeliverabilityRouteImport.update({
  id: '/deliverability',
  path: '/deliverability',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deliverability': typeof AppDeliverabilityRoute
  '/email-finder': typeof AppEmailFinderRoute
  '/lead-finder': typeof AppLeadFinderRoute
  '/leads': typeof AppLeadsRoute
  '/playbook': typeof AppPlaybookRoute
  '/sequences': typeof AppSequencesRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deliverability': typeof AppDeliverabilityRoute
  '/email-finder': typeof AppEmailFinderRoute
  '/lead-finder': typeof AppLeadFinderRoute
  '/leads': typeof AppLeadsRoute
  '/playbook': typeof AppPlaybookRoute
  '/sequences': typeof AppSequencesRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deliverability': typeof AppDeliverabilityRoute
  '/_app/email-finder': typeof AppEmailFinderRoute
  '/_app/lead-finder': typeof AppLeadFinderRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/playbook': typeof AppPlaybookRoute
  '/_app/sequences': typeof AppSequencesRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/deliverability'
    | '/email-finder'
    | '/lead-finder'
    | '/leads'
    | '/playbook'
    | '/sequences'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/deliverability'
    | '/email-finder'
    | '/lead-finder'
    | '/leads'
    | '/playbook'
    | '/sequences'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/campaigns'
    | '/_app/dashboard'
    | '/_app/deliverability'
    | '/_app/email-finder'
    | '/_app/lead-finder'
    | '/_app/leads'
    | '/_app/playbook'
    | '/_app/sequences'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sequences': {
      id: '/_app/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof AppSequencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playbook': {
      id: '/_app/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AppPlaybookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lead-finder': {
      id: '/_app/lead-finder'
      path: '/lead-finder'
      fullPath: '/lead-finder'
      preLoaderRoute: typeof AppLeadFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email-finder': {
      id: '/_app/email-finder'
      path: '/email-finder'
      fullPath: '/email-finder'
      preLoaderRoute: typeof AppEmailFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliverability': {
      id: '/_app/deliverability'
      path: '/deliverability'
      fullPath: '/deliverability'
      preLoaderRoute: typeof AppDeliverabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliverabilityRoute: typeof AppDeliverabilityRoute
  AppEmailFinderRoute: typeof AppEmailFinderRoute
  AppLeadFinderRoute: typeof AppLeadFinderRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppPlaybookRoute: typeof AppPlaybookRoute
  AppSequencesRoute: typeof AppSequencesRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampaignsRoute: AppCampaignsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeliverabilityRoute: AppDeliverabilityRoute,
  AppEmailFinderRoute: AppEmailFinderRoute,
  AppLeadFinderRoute: AppLeadFinderRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppPlaybookRoute: AppPlaybookRoute,
  AppSequencesRoute: AppSequencesRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
